Bugfix/issue 1219 update build system (#1249)
* update third party libgs

diff --git a/.github/workflows/stream.yml b/.github/workflows/stream.yml
--- a/.github/workflows/stream.yml
+++ b/.github/workflows/stream.yml
@@ -12,7 +12,7 @@ jobs:
     with:
       ec2-instance-type: c5.4xlarge
       ec2-image-id: ami-045a86d6d301ab637
-      submodules: 'true'
+      submodules: 'recursive'
       command: |
         echo "download cache_address.tar.gz"
         cd $GITHUB_WORKSPACE
@@ -25,6 +25,12 @@ jobs:
 
         echo "build proton binary"
         ./docker/packager/packager --package-type binary --docker-image-version clang-14 --sanitizer address --proton-build  --cache ccache --ccache_dir $GITHUB_WORKSPACE/ccache --output-dir $GITHUB_WORKSPACE/output
+        
+        if [ ! -f "$GITHUB_WORKSPACE/output/proton" ]; then
+          echo "Compiling proton Failed"
+          exit 127
+        fi
+
         docker run --name static-server -p 8080:80 -v $GITHUB_WORKSPACE/output:/usr/share/nginx/html:ro -d nginx
         cd $GITHUB_WORKSPACE/docker/server
 
diff --git a/.github/workflows/weekly_test.yml b/.github/workflows/weekly_test.yml
--- a/.github/workflows/weekly_test.yml
+++ b/.github/workflows/weekly_test.yml
@@ -12,20 +12,33 @@ jobs:
     outputs:
       command: |
             cd $GITHUB_WORKSPACE
+
             git config user.name "proton-robot"
             git config user.email "proton_robot@timeplus.io"
+
             mkdir $GITHUB_WORKSPACE/ccache
             echo "max_size = 100.0G" > $GITHUB_WORKSPACE/ccache/ccache.conf
+
             ./docker/packager/packager --package-type binary --docker-image-version clang-14 ${SANITIZER:+--sanitizer} $SANITIZER --proton-build  --cache ccache --ccache_dir $GITHUB_WORKSPACE/ccache --output-dir $GITHUB_WORKSPACE/output
+            
+            if [ ! -f "$GITHUB_WORKSPACE/output/proton" ]; then
+              echo "Compiling proton Failed"
+              exit 127
+            fi
+
             docker run --name static-server -p 8080:80 -v $GITHUB_WORKSPACE/output:/usr/share/nginx/html:ro -d nginx
             cd $GITHUB_WORKSPACE/docker/server
+
             docker build . --network host --build-arg single_binary_location_url=http://localhost:8080/proton -t timeplus/proton:testing-$SANITIZER-$GITHUB_SHA
+            
             docker push timeplus/proton:testing-$SANITIZER-$GITHUB_SHA
             cd $GITHUB_WORKSPACE/tests/stream
+
             export PROTON_VERSION=testing-$SANITIZER-$GITHUB_SHA
             env
             pip3 install -r helpers/requirements.txt
             python3 ci_runner.py --debug --settings=redp,nativelog
+            
             tar -zcf ./cache${SANITIZER:+_}$SANITIZER.tar.gz -C $GITHUB_WORKSPACE/ccache .
             aws s3 cp --no-progress ./cache${SANITIZER:+_}$SANITIZER.tar.gz s3://tp-internal/proton/
             cat $GITHUB_WORKSPACE/tests/stream/.status
@@ -40,7 +53,7 @@ jobs:
     with:
       ec2-instance-type: c5.4xlarge
       ec2-image-id: ami-045a86d6d301ab637
-      submodules: 'true'
+      submodules: 'recursive'
       sanitizer: "address"
       tag: 'sanitizer'
       command: |
@@ -59,7 +72,7 @@ jobs:
     with:
       ec2-instance-type: c5.4xlarge
       ec2-image-id: ami-045a86d6d301ab637
-      submodules: 'true'
+      submodules: 'recursive'
       sanitizer: "thread"
       tag: 'sanitizer'
       command: |
@@ -78,7 +91,7 @@ jobs:
     with:
       ec2-instance-type: c5.4xlarge
       ec2-image-id: ami-045a86d6d301ab637
-      submodules: 'true'
+      submodules: 'recursive'
       sanitizer: "memory"
       tag: 'sanitizer'
       command: |
@@ -97,7 +110,7 @@ jobs:
     with:
       ec2-instance-type: c5.4xlarge
       ec2-image-id: ami-045a86d6d301ab637
-      submodules: 'true'
+      submodules: 'recursive'
       sanitizer: "undefined"
       tag: 'sanitizer'
       command: |
@@ -116,7 +129,7 @@ jobs:
     with:
       ec2-instance-type: c5.4xlarge
       ec2-image-id: ami-045a86d6d301ab637
-      submodules: 'true'
+      submodules: 'recursive'
       sanitizer: ""
       tag: 'release'
       command: |
